# Build settings
markdown: kramdown
highlighter: rouge

# Site settings
title: "Hack Education"
description: > # this means to ignore newlines until "email:"
   The History of the Future of Education Technology

url: http://hackeducation.com

email: mail@audreywatters.com
#blog logo
logo: "/assets/images/hack_logo.jpg"
# blog cover
cover: "/assets/images/pigeon_hackeducation.jpg"
covercredits: "https://www.flickr.com/photos/35106989@N08/7934833110"

name: 'Audrey Watters'
author: 'Audrey Watters'
author_image: "/assets/images/author.jpg"

paginate:	5
paginate_path: "/blog/page:num"
permalink: /:categories/:year/:month/:day/:title 

url: "http://hackeducation.com" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@hackeducation'

# social icons and sharing options
social:
  - icon:   twitter
    url:    https://twitter.com/hackeducation
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&url="

  - icon:   facebook
    url:    https://facebook.com/history.future.education
    desc: Like me on facebook
    share_url: http://www.facebook.com/sharer/sharer.php
    share_title: ?title=
    share_link: "?u="

  - icon:   github
    url:    https://github.com/audreywatters/hackeducation.com
    desc:   Fork me on github
    share_url: 
    share_title:
    share_link:

 # - icon:  google-plus
 #   url:   
 #   desc:  
 #   share_url:
 #   share_title:
 #   share_link:

  - icon: rss
    url:  http://hackeducation.com/feed.xml
    desc: Subscribe
    share_url:
    share_title:
    share_link:

  - icon: envelope
    url:  mailto:mail@audreywatters.com
    desc: Email
    share_url:
    share_title:
    share_link:    
  
